server:
  port: ${server.port}
management:
  security: 
    enabled: ${management.security.enabled}
spring:
  profiles: 
    active: master
  application:
    name: film-dev
  data:
    mongodb:
      uri: ${mongoURI} #mongodb://mongo1:27017,mongo2:27019,mongo3:27020/film
